baseURL = 'https://example.org/'
languageCode = 'jp'
title = 'Norelease.dev'
theme = 'simple'

[params]
description = 'Norelease.dev blog'
author = 'Daichi Fujita'

[menu]
[[menu.main]]
name = 'Home'
url = '/'
weight = 1
[[menu.main]]
name = 'Posts'
url = '/posts/'
weight = 2
[[menu.main]]
name = 'About'
url = '/about/'
weight = 3

[markup]
[markup.highlight]
style = 'monokai'
noClasses = false
