languageCode = 'jp'
title = 'Norelease.dev'
theme = 'simple'

[params]
description = 'Norelease.dev blog'
author = 'Daichi Fujita'

[menu]
[[menu.main]]
name = 'Home'
url = '/'
weight = 1
[[menu.main]]
name = 'Posts'
url = '/posts/'
weight = 2
[[menu.main]]
name = 'Scores'
url = '/tags/score/'
weight = 3
[[menu.main]]
name = 'About'
url = '/about/'
weight = 4

[markup]
[markup.highlight]
style = 'monokai'
noClasses = false
[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true
