name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"

      - name: Get base URL
        id: base_url
        run:
          echo "url=https://$(jq -r '.routes[0].pattern' wrangler.json)" >>
          "$GITHUB_OUTPUT"

      - name: Build
        run: hugo --minify --baseURL "${{ steps.base_url.outputs.url }}/"

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
